service: serverless-rest-api
frameworkVersion: ">=1.28.0"
provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  stage: ${opt:stage}
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /register
          method: POST
      - http:
          path: /addArticle
          method: POST
      - http:
          path: /login
          method: POST
      - http:
          path: /getUsers
          method: GET
      - http:
          path: /getArticles
          method: GET
      - http:
          path: /getUserById
          method: GET
      - http:
          path: /getArticlesByTitle
          method: GET
      - http:
          path: /deleteUserById
          method: DELETE
      - http:
          path: /deleteArticleByTitle
          method: DELETE
package:
  patterns:
    - "!*/**"
    - bin/main
